CONFIG = {
    "RAW_MAIN":       "data/raw/screen_time_mental_health.csv",
    "RAW_BDI":        "data/raw/bdi_and_screen_items.csv",
    "PROC_MAIN":      "data/processed/screen_mental_processed.csv",
    "PROC_BDI":       "data/processed/bdi_processed.csv",
    "PROC_FEAT":      "data/processed/features.csv",
    "REPORTS_DIR":    "reports/",
    "MODELS_DIR":     "models/",
    "INSIGHTS_JSON":  "reports/insights.json",
    "EXCEL_OUT":      "reports/screen_mental_report.xlsx",
    "HTML_OUT":       "reports/dashboard.html",
    "SUBJECT_ID":     "subject_id",
    "SEX":            "sex",
    "STI":            "screen_time_index",
    "LEISURE_HRS":    "est_leisure_screen_hours",
    "SQI":            "sleep_quality_index",
    "AVG_SLEEP":      "avg_sleep_hours",
    "MID_SLEEP":      "midsleep_weekend_hours",
    "SOCIAL_JL":      "social_jetlag_hours",
    "BDI_TOTAL":      "bdi_total",
    "DEPRESSED":      "depressed",
    "BDI_ITEMS":      [f"bdi_item_{i:02d}" for i in range(1, 22)],
    "SCREEN_COLS":    ["screen_normal_day_1to6", "screen_weekday_1to6", "screen_weekend_1to6"],
    "SQI_COLS":       ["sqi_fall_asleep_1to6", "sqi_repeated_awake_1to6",
                       "sqi_disturbed_1to6", "sqi_early_awake_1to6"],
    "DEPRESSION_THR": 14,
    "HIGH_SCREEN_HR": 6.0,
    "LOW_SLEEP_HR":   7.0,
    "ANOMALY_CONTAM": 0.05,
    "RANDOM_STATE":   42,
    "TEST_SIZE":      0.2,
    "CV_FOLDS":       5,
}